### ISSUE TITLE
test environment errors installing multi-package plugins

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_python_ci_utilities#17]
Some iRODS plugins, eg. [irods_netcdf](https://github.com/d-w-moore/irods_netcdf) generate multiple packages with interdependencies.  

In such cases, the test hook must currently send a properly ordered list of package files to ci_utilities /
`install_os_packages_from_files_apt` function (in this repo) in order for a test to run, else missing dependencies will be reported and the install of the plugin will fail.

The likely fix is to do the equivalent of `apt install -y P1 P2` as opposed to  `apt install -y P1 ; apt install -y P2`

**Comment by alanking** [comment]
@d-w-moore - Please close if complete.
